// import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import Navbar from '@/components/Navbar';
import { Inter } from 'next/font/google';
import AdminLayout from './admin/page';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>SB Admin 2 - Dashboard</title>
        <link rel="stylesheet" href="/styles/sb-admin-2.min.css" />
        <link
          href="/vendor/fontawesome-free/css/all.min.css"
          rel="stylesheet"
          type="text/css"
        />
        <link href="/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />

        <link
          href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="styleseet"
        />
      </head>
      <body className={inter.className}>
        {/* <Navbar /> */}
        {children}
        <script src="/vendor/jquery/jquery.min.js"></script>
        <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="/vendor/jquery-easing/jquery.easing.min.js"></script>
        <script src="/scripts/sb-admin-2.min.js"></script>
        <script src="/vendor/datatables/jquery.dataTables.min.js"></script>
        <script src="/vendor/datatables/dataTables.bootstrap4.min.js"></script>
        {/* <script src="/scripts/demo/datatables-demo.js"></script>
        <script src="/scripts/demo/datatables-demo.js"></script> */}

      </body>
    </html>
  )
}
